# Generated by Django 5.2.4 on 2025-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sub_category",
            new_name="subcategory",
        ),
        migrations.AddField(
            model_name="orders",
            name="phone",
            field=models.CharField(default="", max_length=111),
        ),
    ]
